M48
; DRILL file {KiCad (6.0.10-0)} date Saturday, March 18, 2023 at 12:34:07 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-18T12:34:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.2475Y-3.2025
X5.2475Y-4.66
X8.8575Y-3.2025
X8.8575Y-4.66
T0
M30
