M48
; DRILL file {KiCad (6.0.10-0)} date Monday, February 27, 2023 at 09:01:11 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-27T21:01:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.2475Y-3.2025
X5.2475Y-4.66
X8.8575Y-3.2025
X8.8575Y-4.66
T0
M30
